#!/bin/bash
#  _____       _                    ___ 
# /  __ \     | |                  /   |
# | /  \/ ___ | | ___  _   _ _ __ / /| |
# | |    / _ \| |/ _ \| | | | '__/ /_| |
# | \__/\ (_) | | (_) | |_| | |  \___  |
#  \____/\___/|_|\___/ \__,_|_|      |_/
#
# Change your PS4 controllers colours!
# 			      v0.1 RC1
# I know this is bad code but send me a pull and ill merge if you got any idea to make this better

while getopts "d,t,h,o,cl" opt; do
      	red=$(find /sys/class/leds* | grep red) && echo $red  > /tmp/red.txt
	green=$(find /sys/class/leds* | grep green) && echo $green  > /tmp/green.txt
	blue=$(find /sys/class/leds* | grep blue) && echo $blue > /tmp/blue.txt
	global=$(find /sys/class/leds* | grep global) && echo $global > /tmp/global.txt
  case $opt in
    d)
	globalt=$(cat /tmp/global.txt)
	redc=$(cat /tmp/red.txt)
	greenc=$(cat /tmp/green.txt)
	bluec=$(cat /tmp/blue.txt)
	echo "Red is $redc"
	echo "Green is $greenc"
	echo "Blue is $bluec"
	echo "Global is $globalt"

	echo 0 > "$globalt"/brightness
	sleep 0.2
	echo 1 > "$globalt"/brightness
	exit 1
      ;;
    c)
	redc=$(cat /tmp/red.txt)
	greenc=$(cat /tmp/green.txt)
	bluec=$(cat /tmp/blue.txt)

	Red='\033[0;31m'
	read -p "Color (1(Red) 2(Green) 3(Blue) 4(Orange) 5(Pink)): " CONDITION;
	Color_Off='\033[0m'

	if [ "$CONDITION" == "1" ]; then
	    clear
		echo 255 > "$redc"/brightness
		echo 0 > "$greenc"/brightness
		echo 0 > "$bluec"/brightness
	        exit
	fi

	if [ "$CONDITION" == "2" ]; then
	    clear
		echo 0 > "$redc"/brightness
		echo 255 > "$greenc"/brightness
		echo 0 > "$bluec"/brightness
	        exit
	fi

	if [ "$CONDITION" == "3" ]; then
	    clear
		echo 0 > "$redc"/brightness
		echo 0 > "$greenc"/brightness
		echo 255 > "$bluec"/brightness
	        exit
	fi

	if [ "$CONDITION" == "4" ]; then
	    clear
		echo 255 > "$redc"/brightness
		echo 165 > "$greenc"/brightness
		echo 0 > "$bluec"/brightness
	        exit
	fi

	if [ "$CONDITION" == "5" ]; then
	    clear
		echo 255 > "$redc"/brightness
		echo 20 > "$greenc"/brightness
		echo 147 > "$bluec"/brightness
	        exit
	fi

      ;;
    o)
	globalt=$(cat /tmp/global.txt)
	echo 0 > "$globalt"/brightness
	exit 1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

echo "Remember: Colour4 needs root!"
echo "  _____       _                    ___  ";
echo " /  __ \     | |                  /   | ";
echo " | /  \/ ___ | | ___  _   _ _ __ / /| | ";
echo " | |    / _ \| |/ _ \| | | | '__/ /_| | ";
echo " | \__/\ (_) | | (_) | |_| | |  \___  | ";
echo "  \____/\___/|_|\___/ \__,_|_|      |_/ ";
echo "                                        ";
echo "                                	      ";
echo "Help:";
echo "c - Show the colour list";
echo "o - Turn off the leds"
echo "d - Debug mode"
	
	
